### ISSUE TITLE
How to implement click event on link

### ISSUE THREAD

**Issue by govardhank** [jfmdev/jqSimpleConnect#1]
How to implement click event on link?
on clicking link change color of link and want to display menu on that link. Pleas help me 

Thanks
Govardhan

**Comment by jfmdev** [comment]
Hi Govardhan,

Thanks your using the library.

If you check the code of the examples (such as [Demo 1](http://jfmdev.github.io/jqSimpleConnect/demo1.html) or [this fiddle](https://jsfiddle.net/9n1tjkxb/)), you would see that all connectors are composed by three `<div>` elements that have the classes `jqSimpleConnect` and `jqSimpleConnect_ID`, where `ID` is an incremental counter (check [this fiddle](https://jsfiddle.net/9n1tjkxb/1/) for a more detailed example). 

So, for defining a click event for a given connect, you must get the `ID` of the connector and assign the click event, such as: `$(".jqSimpleConnect_0").click(function() {console.log("hello");});`.
For defining a click event for all connectors, you can do:  `$(".jqSimpleConnect").click(function() {console.log("hello");});`. 

However, in order to the click events to being triggered correctly, you should assign `z-index` values to all connectors, because the connectors may be overlapped by invisible `<div>` elements. In [this fiddle](https://jsfiddle.net/9n1tjkxb/2/) you can find a more detailed example.

**Comment by govardhank** [comment]
Thank you very much for your quick reply
